### ISSUE TITLE
Suggestion on Logging

### ISSUE THREAD

**Issue by plutocrat** [agjell/sol-tutorials#3]
First of all, thanks for these excellent tutorials. Pulling information out of Discord is like trying to meditate in the middle of a riot. 

I had a couple of suggestions for your section on logging, which I discovered by accident on my own solana journey. 
First of all, you can silence a lot of the noise by the use of the environment variable
export RUST_LOG=WARN
It is set to INFO by default, so setting it to WARN only gives you a fraction of the log entries. 

Secondly, when I was setting this up myself, I used the "--log -" option to output logs to STDOUT, and I'd run my script under screen, so I could duck in and out by detaching and reattaching to the screen session. 
Now the interesting bit. When I used your guide to turn my start script into a systemd service, I found that now the logging was going to the systemd log, and can be viewed with journalctl -u solana. A bonus of this is you can then use /etc/systemd/journald.conf to limit the log size to a certain number of days, MB, GB, etc. So your logs are easy to control without logrotate. 

Hope you find this of interest.

**Comment by agjell** [comment]
Jeez. I haven't seen this, for some reason. Sorry! GitHub newbie here...

I feel your point about log noise. Solana logs are terrible. Unfortunately, the team can ask for the log, or certain stuff in the log, if we need support. It's also necessary for debugging in case of a cluster crash. You are of course free to log as much or little as you want. Considering that I log everything, I'd rather have a separate log. I completely understand logging to STDOUT when your log level is "WARN".

I appreciate the input, though. And thank you for your kind comment about the tutorials! And not the least, my very first GitHub issue... which took me over three months to see 😅
